export const Posts = [
    {
        id: 1,
        title: "Night Life In Aberdern",
        image_url: "/asserts/blogpic_1.jpg",
        paragraph : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor consequat id porta nibh. Mauris nunc congue nisi vitae suscipit tellus mauris a diam. Odio facilisis mauris sit amet massa vitae tortor condimentum. Euismod elementum nisi quis eleifend. Tortor at auctor urna nunc id cursus metus. Lacus sed turpis tincidunt id aliquet risus feugiat in. Nec ullamcorper sit amet risus nullam eget felis eget nunc. Magna fringilla urna porttitor rhoncus dolor purus non. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Diam vel quam elementum pulvinar etiam non. Risus nec feugiat in fermentum posuere urna nec tincidunt. Lectus urna duis convallis convallis tellus id. Tincidunt tortor aliquam nulla facilisi. Nulla facilisi etiam dignissim diam quis.  Id eu nisl nunc mi ipsum faucibus vitae. In massa tempor nec feugiat nisl pretium fusce id velit. Sit amet consectetur adipiscing elit ut. Purus faucibus ornare suspendisse sed nisi lacus. Convallis a cras semper auctor neque vitae. Enim sed faucibus turpis in eu mi. Sed tempus urna et pharetra pharetra massa massa. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Duis tristique sollicitudin nibh sit. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Aenean et tortor at risus viverra adipiscing at in. In pellentesque massa placerat duis ultricies lacus sed turpis. Imperdiet massa tincidunt nunc pulvinar sapien. Pharetra et ultrices neque ornare aenean euismod elementum. Semper quis lectus nulla at volutpat diam ut venenatis. Dictum varius duis at consectetur lorem donec massa sapien faucibus. At in tellus integer feugiat. Vitae semper quis lectus nulla at volutpat diam ut venenatis. Ornare lectus sit amet est placerat in egestas. Proin sed libero enim sed faucibus turpis in eu. Metus vulputate eu scelerisque felis imperdiet. Ultrices sagittis orci a scelerisque. Vitae turpis massa sed elementum tempus. Sed turpis tincidunt id aliquet. Convallis tellus id interdum velit laoreet. Ac odio tempor orci dapibus ultrices in iaculis. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Id consectetur purus ut faucibus. Rhoncus dolor purus non enim praesent elementum. Lectus proin nibh nisl condimentum id venenatis. A condimentum vitae sapien pellentesque. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Lectus quam id leo in vitae turpis massa. Eu tincidunt tortor aliquam nulla. Dictum fusce ut placerat orci nulla pellentesque dignissim enim sit. Tempor orci dapibus ultrices in. Eget gravida cum sociis natoque penatibus et magnis dis parturient.Mollis aliquam ut porttitor leo a. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Pharetra convallis posuere morbi leo urna molestie. Integer vitae justo eget magna fermentum iaculis eu non diam. Suspendisse interdum consectetur libero id faucibus nisl. Ac tortor dignissim convallis aenean et tortor. Lectus proin nibh nisl condimentum id venenatis a condimentum. Auctor eu augue ut lectus arcu bibendum at varius. Tortor vitae purus faucibus ornare. Ut morbi tincidunt augue interdum velit euismod in. Eu facilisis sed odio morbi quis commodo odio aenean sed. Pellentesque habitant morbi tristique senectus et netus et. Ac auctor augue mauris augue neque gravida in fermentum. Et pharetra pharetra massa massa ultricies mi. Eget mauris pharetra et ultrices. Auctor augue mauris augue neque gravida in fermentum et sollicitudin. Duis at tellus at urna condimentum mattis pellentesque. Tristique nulla aliquet enim tortor at auctor urna nunc id. Est ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Nisl purus in mollis nunc sed. Tincidunt arcu non sodales neque sodales ut. Odio morbi quis commodo odio. Dui sapien eget mi proin.",
        featured: true,
        tags: ["lifestyle", ],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "September 2nd, 2023",
      },
      {
        id: 2,
        title: "Things To Do This Winter",
        image_url:"/asserts/blogpic_2.jpg",
        paragraph:
         "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor consequat id porta nibh. Mauris nunc congue nisi vitae suscipit tellus mauris a diam. Odio facilisis mauris sit amet massa vitae tortor condimentum. Euismod elementum nisi quis eleifend. Tortor at auctor urna nunc id cursus metus. Lacus sed turpis tincidunt id aliquet risus feugiat in. Nec ullamcorper sit amet risus nullam eget felis eget nunc. Magna fringilla urna porttitor rhoncus dolor purus non. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Diam vel quam elementum pulvinar etiam non. Risus nec feugiat in fermentum posuere urna nec tincidunt. Lectus urna duis convallis convallis tellus id. Tincidunt tortor aliquam nulla facilisi. Nulla facilisi etiam dignissim diam quis.  Id eu nisl nunc mi ipsum faucibus vitae. In massa tempor nec feugiat nisl pretium fusce id velit. Sit amet consectetur adipiscing elit ut. Purus faucibus ornare suspendisse sed nisi lacus. Convallis a cras semper auctor neque vitae. Enim sed faucibus turpis in eu mi. Sed tempus urna et pharetra pharetra massa massa. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Duis tristique sollicitudin nibh sit. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Aenean et tortor at risus viverra adipiscing at in. In pellentesque massa placerat duis ultricies lacus sed turpis. Imperdiet massa tincidunt nunc pulvinar sapien. Pharetra et ultrices neque ornare aenean euismod elementum. Semper quis lectus nulla at volutpat diam ut venenatis. Dictum varius duis at consectetur lorem donec massa sapien faucibus. At in tellus integer feugiat. Vitae semper quis lectus nulla at volutpat diam ut venenatis. Ornare lectus sit amet est placerat in egestas. Proin sed libero enim sed faucibus turpis in eu. Metus vulputate eu scelerisque felis imperdiet. Ultrices sagittis orci a scelerisque. Vitae turpis massa sed elementum tempus. Sed turpis tincidunt id aliquet. Convallis tellus id interdum velit laoreet. Ac odio tempor orci dapibus ultrices in iaculis. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Id consectetur purus ut faucibus. Rhoncus dolor purus non enim praesent elementum. Lectus proin nibh nisl condimentum id venenatis. A condimentum vitae sapien pellentesque. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Lectus quam id leo in vitae turpis massa. Eu tincidunt tortor aliquam nulla. Dictum fusce ut placerat orci nulla pellentesque dignissim enim sit. Tempor orci dapibus ultrices in. Eget gravida cum sociis natoque penatibus et magnis dis parturient.Mollis aliquam ut porttitor leo a. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Pharetra convallis posuere morbi leo urna molestie. Integer vitae justo eget magna fermentum iaculis eu non diam. Suspendisse interdum consectetur libero id faucibus nisl. Ac tortor dignissim convallis aenean et tortor. Lectus proin nibh nisl condimentum id venenatis a condimentum. Auctor eu augue ut lectus arcu bibendum at varius. Tortor vitae purus faucibus ornare. Ut morbi tincidunt augue interdum velit euismod in. Eu facilisis sed odio morbi quis commodo odio aenean sed. Pellentesque habitant morbi tristique senectus et netus et. Ac auctor augue mauris augue neque gravida in fermentum. Et pharetra pharetra massa massa ultricies mi. Eget mauris pharetra et ultrices. Auctor augue mauris augue neque gravida in fermentum et sollicitudin. Duis at tellus at urna condimentum mattis pellentesque. Tristique nulla aliquet enim tortor at auctor urna nunc id. Est ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Nisl purus in mollis nunc sed. Tincidunt arcu non sodales neque sodales ut. Odio morbi quis commodo odio. Dui sapien eget mi proin.",
        featured: true,
        tags: ["lifestyle"],
        authorImage:"/asserts/my.jpeg",  
        authorName: "Michael Twumasi",
        publishDate: "September 27, 2023",
      },
      {
        id: 3,
        title: "Hike In Scotland",
        image_url:"/asserts/blogpic_3.jpg",
        paragraph:
          "Get out in the summer to explore scotland and it beauties for yourself .Your life will never be the same",
        featured: true,
        tags: ["hike"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "September 20, 2023",
      },
      {
        id: 4,
        title: "Cameras To Use For Photography",
        image_url:"/asserts/blogpic_4.jpg",
        paragraph:
          "As a beginner , there are many cameras to use but we have come up with the cheapest for people to start with .This article helps review cameras",
        featured: true,
        tags: ["photography"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "September 27, 2023",
      },
    
      {
        id: 5,
        title: "Places  To Take Stunning Pictures",
        image_url:"/asserts/jake.jpg",
        paragraph: "DIscover places in scotland to take stunning pictures as a photographer",
        featured: true,
        tags: ["photography"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "October 11, 2023",
      },
      {
        id: 6,
        title: "Places To Hangout In Glasgow",
        image_url:"/asserts/john.jpg",
        paragraph:
          "Discover the fundamentals places to hang out if it is your first time visiting glasgow or you live in glasgow and just looking for a place for a good time",
        featured: false,
        tags: ["lifestyle"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "January 15, 2023",
      },
      {
        id: 7,
        title: "Camp Sites In Scotland",
        image_url:"/asserts/blogpic_5.jpg",
        paragraph:
          "Get in your van and explore scotland . The land of magical places and love",
        featured: false,
        tags: ["hike"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "March 22, 2023",
      },
      {
        id: 8,
        title: "Pose For A Pictures",
        image_url:"/asserts/blogpic_6.jpg",
        paragraph:"Express life in a way it is supposed to be seen .Beauty lies in the eyes of the beholder",
        featured: false,
        tags: ["photography"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "June 9, 2023",
      },
      {
        id: 9,
        title: "Highlands Hike",
        image_url:"/asserts/blogpic_7.jpg",
        paragraph:
          "Travel the highlands of scotland and discover the true beauty of the north.Alot of tourist find it relaxing and peaceful",
        featured: false,
        tags: ["hike"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "August 27, 2023",
      },
      {
        id: 10,
        title: "End Of Year Party",
        image_url:"/asserts/blogpic_8.jpg",
        paragraph:
          "Jump into the festive mood and party in edinburgh for the end of year party.This party has people from all over the world to celebrate the end of year",
        featured: false,
        tags: ["lifestyle"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "October 14, 2023",
      },
      {
        id: 11,
        title: "Scottish Highland Music",
        image_url:"/asserts/blogpic_9.jpg",
         paragraph:
          "Get into the new musics that you are not use to .Scottish music is taking over the globe with a songs with emotional storyline",
        featured: false,
        tags: ["music"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "February 12, 2023",
      },
      {
        id: 12,
        title: "Songs Of The Soul",
        image_url:"/asserts/blogpic_10.jpg",
        paragraph:
          "Song of the soul is an annual music event that happens at the end of the year.The purpose of the event is to showcase scottish music and promote up and coming artist",
        featured: false,
        tags: ["music"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "April 7, 2023",
      },
      {
        id: 13,
        title: "Optimizing Photos",
        image_url:"/asserts/jamill.jpg",
        paragraph:
          "Explore easy and better ways to edit your photos to industry standards. The event helps put photographers in contact and help with the newest ways of doing things",
        featured: false,
        tags: ["photography"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "June 3, 2023",
      },
      {
        id: 14,
        title: "Disco Anthem",
        image_url:"/asserts/blogpic_11.jpg",
        paragraph:
          " Club Xstacy is known for promoting heavy disco music in edinburgh.People who love disco music should visit this place when they are in edinburgh .",
        featured: false,
        tags: ["music"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "July 19, 2023",
      },
      {
        id: 15,
        title:"Jazz Music Bar",
        image_url:"/asserts/blogpic_12.jpg",
        paragraph:
          "Jazz music bar in edinburgh is a place to visit when you are new in edinburgh. They play new revolutionals jazz and it is a place to visit",
        featured: false,
        tags: ["music"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "October 5, 2023",
      },
      {
        id: 16,
        title: "Rock and Roll Bar In Glasgow",
        image_url: "/asserts/blogpic_13.jpg",
        paragraph:
          "The rock and roll bar in glasgow has been in existance since 1991 and it has been part of the music and life scenes in glasgow . Tourist show be on the look out for it",
        featured: false,
        tags: ["music"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "February 3, 2023",
      },
      {
        id: 17,
        title: "Isle Of Skye Hike",
        image_url:"/asserts/blogpic_14.jpg",
         paragraph:
          "A hike in the Isle of Skye will take place in october and anyone who wants to jion can contact hike life who are the organisers of the event",
        featured: false,
        tags: ["hike"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "April 12, 2023",
      },
      {
        id: 18,
        title:"Hike To Arthur's Seat",
        image_url:"/asserts/blogpic_15.jpg",
        paragraph:
          "To hike to arthur's seat is one of the most popular hike spot in edinburgh and scotland.It can be found in the heart of edinburgh city center.",
        featured: false,
        tags: ["hike"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "June 24, 2023",
      },
      {
        id: 19,
        title:"The Cruise In Loch Lomond",
        image_url:"/asserts/blogpic_16.jpg",
       paragraph:
          "The cruise in loch lomond is one of the most popular cruise in scotland and in high demand .Tourist should try and visit it ",
        featured: false,
        tags: ["lifestyle"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "July 13, 2023",
      },
      {
        id: 20,
        title:
          "Ace Hotel",
        image_url:"/asserts/blogpic_17.jpg",
        paragraph:
          "Ace Hotel is a 4star in the middle of edinburgh and comes with alot of amenities.The hotel host alot of charitable events that help solves alot of social problems ",
        featured: false,
        tags: ["lifestyle"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "October 20, 2023",
      },
      {
        id: 21,
        title:
          "One On One With Taylor",
        image_url:"/asserts/taylor.jpg",
        paragraph:
          "Taylor won photographer of the year in the recent ended event.Taylor grew up in Glasgow and started showing interest in photography at a very early age and has progressed to winning an award",
        tags: ["photography"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "February 10, 2023",
      },
      {
        id: 22,
        title: "Relaxing After A Hard Day's Work",
        image_url:"/asserts/blogpic_18.jpg",
        paragraph:
          "Its important to have a relaxed or a chilled time after work .This promotes a healthy life and good for mental health also",
        featured: false,
        tags: ["lifestyle"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "April 5, 2023",
      },
      {
        id: 23,
        title: "Classic Frames",
        image_url:"/asserts/blogpic_19.jpg",
        paragraph:
          "Photography has grown alot and new guys have put in work the come up wih new and improved ways of presenting images",
        featured: false,
        tags: ["photography"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "June 20, 2023",
      },
      {
        id: 24,
        title: "One On One With Lisa",
        image_url:"/asserts/ka.jpg",
        paragraph:
          "Lisa has been a photographer for over 12year and has won alot of awards.She has been doing very well in the industry .",
        featured: false,
        tags: ["photography"],
        authorImage:"/asserts/my.jpeg",
        authorName: "Michael Twumasi",
        publishDate: "August 18, 2023",
      },

]